{{- if and .Values.pulumiAccessToken (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pulumi-exporter.fullname" . }}
  labels:
    app: {{ template "pulumi-exporter.name" . }}
    chart: {{ template "pulumi-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  access-token: {{ .Values.pulumiAccessToken | quote }}
{{- end -}}
