{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pulumi-exporter.serviceAccountName" . }}
  labels:
    app: {{ template "pulumi-exporter.name" . }}
    chart: {{ template "pulumi-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end -}}
