apiVersion: v2
name: pulumi-exporter
icon: https://www.pulumi.com/logos/brand/avatar-on-white.svg
description: A Helm chart for the Pulumi Cloud OpenTelemetry metrics exporter
keywords:
  - pulumi
  - opentelemetry
  - otel
  - metrics
  - exporter
  - prometheus
type: application
version: 0.1.2
appVersion: 0.1.1
home: https://github.com/pulumi-labs/pulumi-exporter/
sources:
  - https://github.com/pulumi-labs/pulumi-exporter/
maintainers:
  - email: engin@pulumi.com
    name: pulumi-labs

annotations:
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/changes: |
    - kind: security
      description: Bump Go minimum version to 1.24.13 to fix CVE-2025-68121 (crypto/tls session resumption)
  artifacthub.io/images: |
    - name: pulumi-exporter
      image: ghcr.io/pulumi-labs/pulumi-exporter:0.1.1
  artifacthub.io/license: MIT
  artifacthub.io/maintainers: |
    - name: pulumi-labs
      email: engin@pulumi.com
